PREFIX type: <http://oxfordsemantic.tech/myDataStore/classes#>
PREFIX prop: <http://oxfordsemantic.tech/myDataStore/properties#>

SELECT ?oldestPerson WHERE {
    ?oldestPerson a type:Person ;
        prop:hasDateOfBirth ?dob
} ORDER BY ASC(?dob) LIMIT 1